services:
  - type: web
    name: prok-backend
    env: python
    rootDir: app/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        value: yVQW9wiwwGw74tdpNhqHX1n-x65UOlxL82ZWMmZJ6nk
      - key: JWT_SECRET_KEY
        value: uE-hmIaQBOYCY3T1fauN83JRQOpLia77wJWMMJRRQY4
      - key: DATABASE_URL
        value: <your-database-url-here>
      - key: PYTHON_VERSION
        value: 3.11.5 